= Brewdis
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:toc: preamble
endif::[]
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/brewdis
:uri-repo: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Real-time inventory demo based on data from https://brewerydb.com[brewerydb.com].

== Getting Started

=== Setup
This demo requires Java 11 or higher and https://www.npmjs.com[npm]

You will also need a https://oss.redislabs.com/redisearch/Quick_Start/[RediSearch] database to run the demo.

To run RediSearch using Docker:
[source,shell]
----
$ docker run -p 6379:6379 redislabs/redisearch:latest
----

=== Running the demo
Clone this git repository and build it:
[source,shell]
----
$ git clone https://github.com/Redislabs-Solution-Architects/brewdis.git
$ cd brewdis
$ ./mvnw clean install
----

==== Locally
Run the application:
[source,shell]
----
$ java -jar server/target/brewdis-server-1.0.0.jar --spring.redis.host=<host> --spring.redis.port=<port>
----

==== Docker
Build the Docker image:
[source,shell]
----
$ cd server
$ mvn dockerfile:build
----

Run the container:
[source,shell]
----
$ docker run  -e "spring.redis.host=docker.for.mac.localhost" -p 8080:8080 redislabs/brewdis
----

=== Configuration

Here are the most common configuration properties:

- `spring.redis.host`: Redis database hostname (default: `localhost`)
- `spring.redis.port`: Redis database port (default: `6379`)
- `inventory.generator.rate`: duration in millis the generator should sleep between inventory updates (default: `100`)
- `availability-radius`: radius to find in-store availability (default: `25 mi`)   

== Architecture

{empty} +

image::https://redislabs-solution-architects.github.io/brewdis/architecture.svg[Brewdis]

{empty} +

== Demo Steps

=== Products
. Launch `redis-cli`
. Show number of documents in RediSearch index:
+
`FT.INFO products`
. Run simple keyword search:
+
`FT.SEARCH products chambly`
+
TIP: `name`, `description`, `breweryName` are phonetic text fields so you will notice results containing words that sound similar. 
. Run prefix search:
+
`FT.SEARCH products chamb*`
. Open http://localhost:8080
. Enter some characters in the Brewery field to retrieve suggestions from RediSearch (e.g. `Unib`)
. Click the `Submit` button
. Refine the search by adding a constraint on the alcohol content (ABV field):
+
`@abv:[7 9]`
. Change the sort-by field to `ABV`
. Click the `+` button on a few beers to start generating inventory for those products

=== Availability
. Click on the map button for one of these beers. It takes you to the availability map for that product
. You can see stores that have that product. Stores in `green` have more than 20, `amber`: 10 to 20, `red`: less than 10

=== Inventory
. Select a store and click on its name in the popup that shows up
. This takes you to the real-tiome inventory for that store
. The `Available to Promise` field is updated in real-time based on current difference between supply and demand.