= Brewdis
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/brewdis
:uri-repo: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Real-time inventory demo based on data from https://brewerydb.com[brewerydb.com].

== Run the demo

[source,shell]
----
git clone https://github.com/Redislabs-Solution-Architects/brewdis.git
cd brewdis
docker-compose up
----

Access the demo at http://localhost[]

== Demo Steps

=== Presentation

An overview of the business context and demo architecture is available at http://pages.brewdis.demo.redislabs.com/[pages.brewdis.demo.redislabs.com]

TIP: Hit the `S` key to open speaker notes 

=== Products
. Launch `redis-cli`
. Show number of documents in RediSearch index:
+
`FT.INFO products`
. Run simple keyword search:
+
`FT.SEARCH products chambly`
+
TIP: `name`, `description`, `breweryName` are phonetic text fields so you will notice results containing words that sound similar. 
. Run prefix search:
+
`FT.SEARCH products chamb*`
. Open http://localhost[]
. Enter some characters in the Brewery field to retrieve suggestions from RediSearch (e.g. `Unib`)
. Click the `Submit` button
. Refine the search by adding a constraint on the alcohol content (ABV field):
+
`@abv:[7 9]`
. Change the sort-by field to `ABV` and click `Submit`

=== Availability
. Click `Availability` on one of the search results. This takes you to the availability map for that product. 
. The map shows stores near you where the selected product is currently available.
. Stores in `green` have more than 20 in stock, `amber`: 10 to 20, `red`: less than 10

=== Inventory
. Click on a store and then on the link that pops up 
. This takes you to the real-time inventory for that store
. The *Available to Promise* field is updated in real-time based on current difference between supply (*On Hand*) and demand (*Reserved + Allocated + Virtual Hold*).


== Develop

=== Configuration

The app server configuration is stored in `server/src/main/resources/application.properties`

Here are the most common configuration options:

- `spring.redis.host`: Redis database hostname (default: `localhost`)
- `spring.redis.port`: Redis database port (default: `6379`)
- `inventory.generator.rate`: duration in millis the generator should sleep between inventory updates (default: `100`)
- `availability-radius`: radius to find in-store availability (default: `25 mi`)   

=== Architecture

{empty} +

image::https://redislabs-solution-architects.github.io/brewdis/images/brewdis-architecture.svg[Brewdis]

{empty} +
