= Brewdis
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/brewdis
:uri-repo: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Real-time inventory demo based on data from https://brewerydb.com[brewerydb.com].

== Run the demo

[source,shell]
----
git clone https://github.com/Redislabs-Solution-Architects/brewdis.git
cd brewdis
docker-compose up
----

Access the demo at http://localhost[]

== Demo Steps

=== Presentation

An overview of the business context and demo architecture is available at http://pages.brewdis.demo.redislabs.com/[pages.brewdis.demo.redislabs.com]

TIP: Hit the `S` key to open speaker notes 

=== Products
. Launch `redis-cli`
. Show number of documents in RediSearch index:
+
`FT.INFO products`
. Run simple keyword search:
+
`FT.SEARCH products chambly`
+
TIP: `name`, `description`, `breweryName` are phonetic text fields so you will notice results containing words that sound similar. 
. Run prefix search:
+
`FT.SEARCH products chamb*`
. Open http://localhost[]
. Enter a simple keyword search, e.g. `chambly`. Note highlighted matches.
. Expand the filter panel by clicking on the filter button:
+
image::http://pages.brewdis.demo.redislabs.com/images/filter_list-24px.svg[]
. Enter some characters in the Brewery field to retrieve suggestions from RediSearch (e.g. `Unib`)
. Click the `Submit` button
. Refine the search by adding a constraint on the alcohol content (ABV field):
+
`@abv:[7 9]`
. Change the sort-by field to `ABV` and click `Submit`

=== Availability
. Click `Availability` on one of the search results. This takes you to the availability map for that product. 
. The map shows stores near you where the selected product is currently available.
. Stores in `green` have more than 20 in stock, `amber`: 10 to 20, `red`: less than 10

=== Inventory
. Click on a store and then on the link that pops up 
. This takes you to the real-time inventory for that store
. The *Available to Promise* field is updated in real-time based on current difference between supply (*On Hand*) and demand (*Reserved + Allocated + Virtual Hold*).


== Configuration

The app server is built with Spring Boot which can be configured different ways: https://docs.spring.io/spring-boot/docs/2.2.x/reference/html/spring-boot-features.html#boot-features-external-config[Spring Boot Externalized Configuration].
Depending on the way you're running the demo you can either:

- create a `application.properties` file based on the https://github.com/Redislabs-Solution-Architects/brewdis/blob/master/brewdis-api/src/main/resources/application.properties[one that ships with Brewdis]
- specify JVM arguments like this:
[source,shell]
----
java -jar brewdis.jar --spring.redis.host=localhost --spring.redis.port=6379 ...
----
- use environment variables:
[source,shell]
----
export spring.redis.host=localhost
export spring.redis.port=8080
export ...
java -jar brewdis.jar
----

Here are the most common configuration options for this demo:

- `spring.redis.host`: Redis database hostname (default: `localhost`)
- `spring.redis.port`: Redis database port (default: `6379`)
- `stomp.host`: Websocket server hostname (default: `localhost`)
- `stomp.port`: Websocket server port (default: `8080`)
- `stomp.protocol`: Websocket protocol (default: `ws`). Use `wss` for secure websockets
- `inventory.generator.rate`: duration in millis the generator should sleep between inventory updates (default: `100`)
- `availability-radius`: radius to find in-store availability (default: `25 mi`)   

== Architecture

{empty} +

image::https://redislabs-solution-architects.github.io/brewdis/images/brewdis-architecture.svg[Brewdis]

{empty} +
