= Real-Time Inventory
:revnumber: {project-version}
ifndef::imagesdir[:imagesdir: images]

== Introduction

[%step]
* What is retail inventory?
* Real-time inventory architecture
* Demo

== Retail Inventory

*What* is available *Where*

[%step]
* *What:* Products
* *Where:* Stores and DCs

[NOTE.speaker]
--
* A product might have many SKUs (the same shirt has different SKUs for size/color/style combinations). Some retailers reference 1M+ SKUs
* Distribution Center AKA Fulfillment Center AKA Warehouse
--

== Inventory Consumers

[%step]
* e-Commerce
* Find/Reserve in Store
* Order Sourcing
* Store Allocation

== Item Availability

[%step]
* Buckets for supply & demand tracking
* What's really available?
* *Available to Promise (ATP)*: Supply - Demand

[NOTE.speaker]
--
* How do we decide if we can show a piece of inventory as available on the website?
* Factors: on hand (actual inventory), price, product, store, sales velocity, cost to fulfill, order status, laws and regulations, location
--

== Inventory Challenges

[%step]
** Volume
** Velocity
** Geo-Distribution

[NOTE.speaker]
--
* Volume: 1000 Stores * 100,1000 SKUS => 100M Store/SKU combinations
* Velocity: 1000s inventory updates/sec
* Geo-Distribution: maintain consistency between store(s) and data centers
--

== Architecture

image::inventory-architecture.svg[]

== Retail Inventory Demo

[%step]
* Brewdis: beer retailer
* 3500 Stores worldwide
* 30,000 SKUs

== Demo Aspects 

[%step]
* Product Catalog
* Item Availability
* Real-Time Inventory

[NOTE.speaker]
--
* Product Catalog: full text + secondary indexing (tag, numeric, geo)
* Item availability: what is available and where? geo filters
* Real-Time Inventory: streaming store/sku updates 
-- 

== Data Model

* `products`
* `stores`
* `inventory`

== Products Index

[source,plaintext]
----
FT.CREATE products SCHEMA
   sku TAG SORTABLE
   name TEXT
   description TEXT PHONETIC dm:en
   ...
----

[source,plaintext]
----
FT.ADD products "product:<sku>" 1.0 FIELDS ...
---- 

== Stores Index

[source,plaintext]
----
FT.CREATE stores SCHEMA
   store TAG SORTABLE
   name TEXT
   location GEO
   market TAG SORTABLE
   ...
----

[source,plaintext]
----
FT.ADD stores "store:<id>" 1.0 FIELDS ...
---- 

== Inventory Index

[source,plaintext]
----
FT.CREATE inventory SCHEMA
   store TAG SORTABLE
   sku TAG SORTABLE
   location GEO
   availableToPromise NUMERIC SORTABLE
   ...
----

[source,plaintext]
----
FT.ADD inventory "inventory:<store>:<sku>" 1.0 FIELDS ...
----

== Demo Architecture

image::brewdis-architecture.svg[]

== Inventory Generator

[source,plaintext]
----
XADD inventory-update-stream * store 7 sku B5 allocated 4
----

== Inventory Manager

[%step]
[source,plaintext]
----
XREAD STREAMS inventory-updates
----
[source,plaintext]
----
FT.GET inventory inventory:7:B5
----
[source,plaintext]
----
FT.ADD inventory inventory:7:B5 1.0 FIELDS atp 20 allocated 16
----
[source,plaintext]
----
XADD inventory-stream * id 7:B5 atp 20 allocated 16
----

== Querying Inventory

Availability lookup

[source,plaintext]
----
FT.GET inventory inventory:7:B5
----

== Querying Inventory

Local availability

[source,plaintext]
----
FT.SEARCH inventory "@location:{-118.2 34.0 10 mi}"
----

== Querying Inventory

Regional availability levels

[source,plaintext]
----
FT.AGGREGATE inventory
   "@sku:{02 93 13} @location:[-118.2 34.0 25 mi]"
   GROUPBY 1 @sku REDUCE SUM 1 @atp AS atp
   SORTBY 2 @atp DESC
----